# Generated by Django 3.2.11 on 2022-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='file',
            field=models.FileField(default=None, upload_to='city/'),
        ),
    ]
