# Generated by Django 3.2.11 on 2022-01-19 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.city'),
        ),
    ]
