# Generated by Django 3.2.11 on 2022-01-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_assignment_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
