# Generated by Django 3.2.11 on 2022-01-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_operator_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='lat',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='assignment',
            name='long',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
    ]
