# Generated by Django 3.2.11 on 2022-01-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220119_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='long',
            new_name='lng',
        ),
    ]
