# Generated by Django 3.2.11 on 2022-01-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_long_assignment_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='unique_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
