# Generated by Django 3.2.11 on 2022-01-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_operator_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='is_first',
            field=models.BooleanField(default=True),
        ),
    ]
