# Generated by Django 3.2.11 on 2022-01-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20220120_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlong',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='latlong',
            name='lng',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
