# Generated by Django 3.2.11 on 2022-01-20 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220120_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='latlong',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
