# Generated by Django 3.2.11 on 2022-01-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_latlong_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latlong',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_items', to='base.assignment'),
        ),
    ]
