# Generated by Django 3.2.11 on 2022-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_latlong_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
